rocketmq:
  name-server: ${CARBON_RMQ_NAMESRV:192.168.100.128:9876}
  producer:
    group: carbon-system
    send-message-timeout: 300000

#spring配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${CARBON_MYSQL_HOST:192.168.100.128}:${CARBON_MYSQL_PORT:3333}/${CARBON_MYSQL_DB:carbon}?useUnicode=true&characterEncoding=utf8
      username: ${CARBON_MYSQL_USER:root}
      password: ${CARBON_MYSQL_PASSWORD:root}
  #redis
  redis:
    host: ${CARBON_REDIS_HOST:192.168.100.128}
    port: ${CARBON_REDIS_PORT:6379}
    password: ${CARBON_REDIS_PASSWORD:}
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: ${CARBON_NACOS_ADDR:192.168.100.128:8848}

# 日志
logging:
  level:
    com.carbon.trade.mapper: debug
