#服务配置
server:
  port: 9091
#spring配置
  tomcat:
    max-http-form-post-size: 50MB
spring:
  #1.应用配置
  profiles:
    # 本地运行使用dev，打包时使用test
        active: dev
#    active: test
  application:
    name: carbon-gate #指定服务名
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.100.128:3333/carbon?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
  redis:
    host: 192.168.100.128
    port: 6379
    # password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.128:8848
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

#配置路由规则
zuul:
  host:
    connect-timeout-millis: 60000  #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000  #socket超时
  routes:
    #路由id
    authCenter: #认证中心
      path: /authCenter/** #配置请求URL的请求规则
      serviceId: carbon-auth #指定Eureka注册中心中的服务id
      stripPrefix: false
      sentiviteHeaders:   #将指定路由的敏感头设置为空
      customSensitiveHeaders: true #对指定路由开启自定义敏感头
    system: #系统
      path: /system/**
      serviceId: carbon-system
      stripPrefix: false
      sentiviteHeaders:
      customSensitiveHeaders: true
    assets: #资产
      path: /assets/**
      serviceId: carbon-assets
      stripPrefix: false
      sentiviteHeaders:
      customSensitiveHeaders: true
    trade: #交易
      path: /trade/**
      serviceId: carbon-trade
      stripPrefix: false
      sentiviteHeaders:
      customSensitiveHeaders: true


# 设置 feign 超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000

knife4j:
  nacos:
    enable: true
    serviceUrl: http://192.168.100.128:8848/nacos/
