spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${CARBON_MYSQL_HOST:localhost}:${CARBON_MYSQL_PORT:3306}/${CARBON_MYSQL_DB:carbon}?useUnicode=true&characterEncoding=utf8
      username: ${CARBON_MYSQL_USER:root}
      password: ${CARBON_MYSQL_PASSWORD:root}
  redis:
    host: ${CARBON_REDIS_HOST:localhost}
    port: ${CARBON_REDIS_PORT:6379}
    password: ${CARBON_REDIS_PASSWORD:}
  cloud:
    nacos:
      discovery:
        server-addr: ${CARBON_NACOS_ADDR:localhost:8848}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

knife4j:
  nacos:
    enable: true
    serviceUrl: http://${CARBON_NACOS_ADDR:localhost:8848}/nacos/

logging:
  level:
    com.carbon.gate.mapper: debug

zuul:
  routes:
    trade:
      url: http://localhost:9005
      stripPrefix: false
